#!/bin/bash

source service.env

SERVICE_ENV='\
ARG SERVICE_NAME\
ARG SERVICE_VERSION\
ARG SERVICE_HOST\
ARG SERVICE_PORT\
ENV SERVICE_NAME='"${SERVICE_NAME}"'\
ENV SERVICE_VERSION='"${SERVICE_VERSION}"'\
ENV SERVICE_HOST='"${SERVICE_HOST}"'\
ENV SERVICE_PORT='"${SERVICE_PORT}"'\
ENV SERVICE_HOME='"${SERVICE_HOME}"''

DOCKERFILE=Dockerfile

sed -e 's+SERVICE_ENV+'"${SERVICE_ENV}"'+g' Dockerfile.in > ${DOCKERFILE}
