#!/bin/bash

source service.env

SERVICE_ENV='\
ARG SERVICE_NAME\
ARG SERVICE_VERSION\
ARG SERVICE_HOST\
ARG SERVICE_PORT\
ENV SERVICE_NAME='"${SERVICE_NAME}"'\
ENV SERVICE_VERSION='"${SERVICE_VERSION}"'\
ENV SERVICE_HOST='"${SERVICE_HOST}"'\
ENV SERVICE_PORT='"${SERVICE_PORT}"'\
ENV SERVICE_HOME='"${SERVICE_HOME}"''

DOCKERFILE=Dockerfile

sed -e 's+SERVICE_ENV+'"${SERVICE_ENV}"'+g' Dockerfile.in > ${DOCKERFILE} && \
docker build -f ${DOCKERFILE} -t "${SERVICE_NAME}:${SERVICE_VERSION}" \
    --build-arg SERVICE_NAME=${SERVICE_NAME} --build-arg SERVICE_VERSION=${SERVICE_VERSION} \
    --build-arg SERVICE_HOST=${SERVICE_HOST} --build-arg SERVICE_PORT=${SERVICE_PORT} \
	--build-arg SERVICE_HOME=${SERVICE_HOME} \
    ${DOCKER_BUILD_ARGS} \
    .
