#!/bin/bash

source service.env

APP_DOCKER_ENV="\n\
ARG SERVICE_NAME\n\
ARG SERVICE_VERSION\n\
ARG SERVICE_HOST\n\
ARG SERVICE_PORT\n\
ENV SERVICE_NAME=${SERVICE_NAME}\n\
ENV SERVICE_VERSION=${SERVICE_VERSION}\n\
ENV SERVICE_HOST=${SERVICE_HOST}\n\
ENV SERVICE_PORT=${SERVICE_PORT}\n\
ENV SRV_HOME=\/srv\/${SERVICE_NAME}\n"

DOCKERFILE=Dockerfile

sed -e 's+APP_DOCKER_ENV+'"$APP_DOCKER_ENV"'+g' Dockerfile.in > ${DOCKERFILE} && \
docker build -f ${DOCKERFILE} -t "${SERVICE_NAME}:${SERVICE_VERSION}" \
    --build-arg SERVICE_NAME=${SERVICE_NAME} --build-arg SERVICE_VERSION=${SERVICE_VERSION} \
    --build-arg SERVICE_HOST=${SERVICE_HOST} --build-arg SERVICE_PORT=${SERVICE_PORT} \
    ${DOCKER_BUILD_ARGS} \
    .
