---
api-key: ""
cainfo: ""
capath: ""
direct-domains: []
dns: []
fast-fail-regexps: []
log-stats: 0
logfile: ""
max-logsize: 0
metrics-address: "localhost:0"
no-autodetect: false
tunnel-pool: false
no-ssl-bump-domains: []
pac: ""
pidfile: ""
proxy: ""
proxy-tunnel: false
proxy-userpwd: ""
readyfile: ""
region: "us-west"
shared-tunnel: false
tunnel-domains: []
tunnel-name: ""
user: ""
verbose: 0
