FROM <?= from ?>

ARG SERVICE_NAME
ARG SERVICE_VERSION
ARG SERVICE_HOST
ARG SERVICE_PORT
ENV SERVICE_NAME=<?= SERVICE_NAME ?>
ENV SERVICE_VERSION=<?= SERVICE_VERSION ?>
ENV SERVICE_HOST=<?= SERVICE_HOST ?>
ENV SERVICE_PORT=<?= SERVICE_PORT ?>
ENV SERVICE_HOME=<?= SERVICE_HOME ?>

<? if (from.includes('ubuntu')) {?>
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
	ca-certificates \
	wget
<? } else { ?>
RUN apk update && \
    apk add ca-certificates && \
    update-ca-certificates && \
    apk add openssl && \
    apk add bash
<? } ?>

WORKDIR $SERVICE_HOME

ENV SC_PKG="sc-${SERVICE_VERSION}-linux.tar.gz"
RUN wget https://saucelabs.com/downloads/${SC_PKG} && \
	tar xvf ${SC_PKG} && rm -f ${SC_PKG}

<? if (from.includes('ubuntu')) {?>
RUN ln -s ${SERVICE_HOME}/sc-${SERVICE_VERSION}-linux/bin/sc /sc
<? } ?>

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

EXPOSE 4445
EXPOSE 8032

ENTRYPOINT ["/entrypoint.sh"]
