{
 "title": "Sauce Connect",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Tunnel Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sauce_connect_connections_total",
     "legendFormat": "{{conn}}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(sauce_connect_sent_bytes[$__rate_interval])*-1)",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "sum(rate(sauce_connect_received_bytes[$__rate_interval]))",
     "legendFormat": "Incoming"
    }
   ]
  },
  { "title": "HTTP Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Request Rate by HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(sauce_connect_http_requests_total{code=~\"1..\"}[$__rate_interval]))",
     "legendFormat": "1XX"
    },
    {
     "expr": "sum(rate(sauce_connect_http_requests_total{code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(sauce_connect_http_requests_total{code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(sauce_connect_http_requests_total{code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(sauce_connect_http_requests_total{code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Request Size - 2XX Codes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(sauce_connect_http_request_size_bytes_bucket{code=~\"2..\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Latency - 2XX Codes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(sauce_connect_http_request_duration_seconds_bucket{code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}